# Generated by Django 3.2 on 2021-04-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meals_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'meal', 'verbose_name_plural': 'meals'},
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='preperation_time',
            new_name='preparation_time',
        ),
    ]
