# Generated by Django 3.2.3 on 2021-07-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='chefs',
            options={'verbose_name': 'chef', 'verbose_name_plural': 'chefs'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'verbose_name': 'why choose us', 'verbose_name_plural': 'why choose us'},
        ),
    ]
